### ISSUE TITLE
how can I get local file modification time when using ngx_lua 

### ISSUE THREAD

**Issue by david001-yang** [openresty/ngx_openresty#114]
In io and os module, I cannot find any api to support that. thanks very much.

**Comment by dol** [comment]
IMHO this is not exposed at the moment. You could compile the ['filesystem' rocks](https://luarocks.org/modules/hisham/luafilesystem) into your Openresty lua_package_cpath path.

An other option is to open a new issue in the [openresty/lua-nginx-module](https://github.com/openresty/lua-nginx-module).
An possible integration could like like:
Similar to [ngx_http_lua_open_and_stat_file](https://github.com/openresty/lua-nginx-module/blob/5b35451cd103bda49873af54d9448587203d51bf/src/ngx_http_lua_util.h#L180) a new ffi method could be added and exposed via [openresty/lua-resty-core](https://github.com/openresty/lua-resty-core).

@david001-yang Could you explain what use case do you have?

**Comment by agentzh** [comment]
@david001-yang Yeah, be careful about fetching file modification times upon hot code paths (like upon every request) since it involves a (stat) system call which is inevitably expensive and could become a bottleneck.

BTW, it's better to ask such questions on the openresty-en mailing list: https://openresty.org/#Community Thanks for your cooperation :)

**Comment by david001-yang** [comment]
Thanks very much, we don't need to get file mtime now, we choose to use proxy cache to do it. thanks again for your help.  dol and agentzh ^_^
