### ISSUE TITLE
Mac 10.11 编译 1.9.3.1出错

### ISSUE THREAD

**Issue by nickcen** [openresty/ngx_openresty#122]
openssl通过homebrew安装

./configure --with-openssl=/usr/local/Cellar/openssl/1.0.2d_1

make的时候出错，找不到对应的.h和.a文件，修改文件
/usr/local/ngx_openresty-1.9.3.1/bundle/nginx-1.9.3/auto/lib/openssl/conf文件的定义解决的。

```
CORE_INCS="$CORE_INCS $OPENSSL/include"
CORE_DEPS="$CORE_DEPS $OPENSSL/include/openssl/ssl.h"
CORE_LIBS="$CORE_LIBS $OPENSSL/lib/ssleay32.lib"
CORE_LIBS="$CORE_LIBS $OPENSSL/lib/libeay32.lib"


CORE_INCS="$CORE_INCS $OPENSSL/include"
CORE_DEPS="$CORE_DEPS $OPENSSL/include/openssl/ssl.h"
CORE_LIBS="$CORE_LIBS $OPENSSL/lib/libssl.a"
CORE_LIBS="$CORE_LIBS $OPENSSL/lib/libcrypto.a"
```

**Comment by agentzh** [comment]
@nickcen Please, no Chinese here. This place is considered English only. If you really want to use Chinese, please join the openresty (Chinese) mailing list instead. Please see https://openresty.org/#Community

Regarding your question, you misused the `--with-openssl=DIR` option. The DIR path there must be the *source* tree of OpenSSL instead of the installation tree (containing the built binaries as well as headers). To quote the usage info printed by `./configure --help`:

```
  --with-openssl=DIR                 set path to OpenSSL library sources
```

Note the "sources" word above.

On the other hand, if you want the OpenResty build to use the installed OpenSSL library (via homebrew, for example), then you really specify the `--with-cc-opt="-I/path/to/openssl/include"` and `--with-ld-opt="-L/path/to/openssl/lib -Wl,-rpath,/path/to/openssl/lib"` options instead.

Check out the following document for more details on building OpenResty on Mac OS X:

https://openresty.org/#Download

BTW, my daily machine is a macbook ;)

**Comment by xwfang** [comment]
我也遇到这个问题 只能用 --with-cc-opt 和 --with-ld-opt 解决
