### ISSUE TITLE
Install OpenResty under OS X EI Capitan failed

### ISSUE THREAD

**Issue by JounQin** [openresty/ngx_openresty#123]
There is no *openssl* directory under OS X EI Capitan and I've tried many versions of the OpenResty.

[Error File](https://gist.github.com/JounQin/58c7d89cea1a1f3c56b0)

**Comment by agentzh** [comment]
@JounQin I think you can just install the OpenSSL library via homebrew or something like that.

**Comment by agentzh** [comment]
@JounQin BTW, the contents in the file `build/nginx-1.9.3/objs/autoconf.err` in your OpenResty source directory can be helpful when debugging.

Oh, please consider using 3rd-party paste services like gist.github.com to avoid flooding the ticket board. You can just share the links here. Thanks for your cooperation.

**Comment by JounQin** [comment]
I've installed OpenSSL a long time ago and even if I use **--with-openssl="/usr/local/Cellar/openssl/1.0.2d_1"** however the error still persists.

[Error Files](https://gist.github.com/JounQin/4655d268a2beb4aa3e6c)

**Comment by agentzh** [comment]
@JounQin You misused the `--with-openssl=DIR` option. The `DIR` path there must be the *source* tree of OpenSSL instead of the *installation* tree (containing the built binaries as well as headers). To quote the usage info printed by `./configure --help`:

```
  --with-openssl=DIR                 set path to OpenSSL library sources
```

Note the "sources" word above.

On the other hand, if you want the OpenResty build to use the installed OpenSSL library (via homebrew, for example), then you really specify the `--with-cc-opt="-I/path/to/openssl/include"` and `--with-ld-opt="-L/path/to/openssl/lib -Wl,-rpath,/path/to/openssl/lib"` options instead.

**Comment by JounQin** [comment]
Thanks a lot!I've installed the OpenResty successfully under your guidance!
